renlabs-dev/subspace-network

.github/workflows/build-docker.yml, .github/workflows/check.yml, Dockerfile, pallets/subspace/rpc/runtime-api/src/lib.rs
Integrates our dockerfile and workflow with sccache to reduce compile times.
=> feat: added sccache to workflow and dockerfile

.github/workflows/build-docker.yml, Dockerfile
Adds a link to the dockerfile snapshot folder.
=> fix(dockerfile): fix sccache arguments

pallets/subspace/src/lib.rs, pallets/subspace/src/registration.rs, pallets/subspace/src/subnet.rs, pallets/subspace/tests/mock.rs, pallets/subspace/tests/subnets.rs
=> fix: resolve subnet limit bugs

Cargo.lock, Cargo.toml, pallets/subspace/Cargo.toml, pallets/subspace/src/global.rs, pallets/subspace/src/lib.rs, pallets/subspace/src/math.rs, pallets/subspace/src/migrations.rs, pallets/subspace/src/module.rs, pallets/subspace/src/profit_share.rs, pallets/subspace/src/registration.rs, pallets/subspace/src/staking.rs, pallets/subspace/src/step.rs, pallets/subspace/src/step/yuma.rs, pallets/subspace/src/subnet.rs, pallets/subspace/tests/burn.rs, pallets/subspace/tests/mock.rs, pallets/subspace/tests/profit_share.rs, pallets/subspace/tests/step_linear.rs, pallets/subspace/tests/step_yuma.rs, pallets/subspace/tests/subnet.rs
Adds the first implementation of the YUMA consensus to Commune's blockchain.
Closes #39.
=> feat: impl first version of yuma consensus

.vscode/settings.json, Cargo.lock, node/Cargo.toml, pallets/subspace/Cargo.toml, pallets/subspace/rpc/runtime-api/src/lib.rs, pallets/subspace/rpc/src/lib.rs, pallets/subspace/src/autogen_weights.rs, pallets/subspace/src/benchmarking.rs, pallets/subspace/src/global.rs, pallets/subspace/src/lib.rs, pallets/subspace/src/migrations.rs, pallets/subspace/src/module.rs, pallets/subspace/src/registration.rs, pallets/subspace/src/staking.rs, pallets/subspace/src/step.rs, pallets/subspace/src/subnet.rs, pallets/subspace/src/voting.rs, pallets/subspace/tests/mock.rs, pallets/subspace/tests/step_linear.rs, pallets/subspace/tests/step_yuma.rs, pallets/subspace/tests/subnet.rs, pallets/subspace/tests/voting.rs, runtime/Cargo.toml, runtime/src/lib.rs
=> new Proposal System big merge

pallets/subspace/src/global.rs, pallets/subspace/src/migrations.rs, pallets/subspace/src/voting.rs
Moves subnet 0 to vote mode and erases votes for expired proposals.
=> feat: move subnet 0 to vote mode

pallets/subspace/src/autogen_weights.rs, pallets/subspace/src/benchmarking.rs, pallets/subspace/src/lib.rs, pallets/subspace/src/migrations.rs, pallets/subspace/src/registration.rs, pallets/subspace/src/staking.rs, pallets/subspace/src/step.rs, pallets/subspace/src/step/yuma.rs, pallets/subspace/src/subnet.rs, pallets/subspace/src/voting.rs, pallets/subspace/tests/burn.rs, pallets/subspace/tests/mock.rs, pallets/subspace/tests/registration.rs, pallets/subspace/tests/staking.rs, pallets/subspace/tests/step_linear.rs, pallets/subspace/tests/step_yuma.rs, pallets/subspace/tests/subnet.rs, pallets/subspace/tests/weights.rs
Corrects the yuma calculation to use the correct stake ordering.
=> fix(yuma): use correct stake

pallets/subspace/src/lib.rs, pallets/subspace/src/registration.rs, pallets/subspace/src/subnet.rs, pallets/subspace/src/voting.rs, pallets/subspace/tests/burn.rs, pallets/subspace/tests/delegate_staking.rs, pallets/subspace/tests/mock.rs, pallets/subspace/tests/profit_share.rs, pallets/subspace/tests/registration.rs, pallets/subspace/tests/staking.rs, pallets/subspace/tests/step_linear.rs, pallets/subspace/tests/step_yuma.rs, pallets/subspace/tests/subnet.rs, pallets/subspace/tests/weights.rs
Always use subnet changeset to perform updates to parameters.
=> feat: always validate subnet params

pallets/subspace/src/lib.rs, pallets/subspace/src/migrations.rs, runtime/src/lib.rs
This PR:
* Set the `MaxWeightsAllowed` storage value to 1024
* Set `FounderShare` of subnet 0 to 12%
* Increase registration cost
* set `TargetRegistrationsPerInterval` to 5
* set `MinBurn` to `10_000_000_000`
* set `AdjustmentAlpha` to `AdjustmentAlpha * 1.1`
Reference: https://governance.communeai.org/#proposed-changes-to-incentive-mechanisms
=> feat(pallets/subspace): start v6 migration

pallets/subspace/src/migrations.rs
Updates all founder share values to minimum of floor founder share
=> feat(pallets/subpsace): add migrations to v6 of founder share values

pallets/subspace/src/lib.rs, pallets/subspace/src/step.rs, pallets/subspace/tests/step_linear.rs, pallets/subspace/tests/subnet.rs
When the epoch is reached for subnet 0 (s0), we must calculate the founder share defined for s0 and add it to a global storage value GlobalDaoTreasury (u64).
=> feat(pallets/subspace): update global treasure when have linear epoch

pallets/subspace/src/lib.rs, pallets/subspace/src/module.rs, pallets/subspace/src/registration.rs, pallets/subspace/src/set_weights.rs, pallets/subspace/src/staking.rs, pallets/subspace/src/step.rs, pallets/subspace/src/step/yuma.rs, pallets/subspace/src/subnet.rs, pallets/subspace/tests/burn.rs, pallets/subspace/tests/delegate_staking.rs, pallets/subspace/tests/mock.rs, pallets/subspace/tests/profit_share.rs, pallets/subspace/tests/registration.rs, pallets/subspace/tests/step_linear.rs, pallets/subspace/tests/step_yuma.rs, pallets/subspace/tests/subnet.rs, pallets/subspace/tests/weights.rs
This PR organizes the subnet file, and takes out useless set and get functions
=> refac: useless code cleanup

CHANGELOG, pallets/governance/src/lib.rs, pallets/subspace/src/global.rs, pallets/subspace/src/lib.rs, pallets/subspace/src/migrations.rs, pallets/subspace/src/registration.rs, pallets/subspace/src/step.rs, pallets/subspace/src/subnet.rs, pallets/subspace/tests/burn.rs, pallets/subspace/tests/mock.rs, pallets/subspace/tests/registration.rs, pallets/subspace/tests/step_linear.rs, pallets/subspace/tests/subnet.rs, pallets/subspace/tests/voting.rs, pallets/subspace/tests/weights.rs, runtime/src/lib.rs
This PR is delivering compatibility with the latest [mainnet release](https://github.com/commune-ai/subspace/releases/tag/v1.7.5).
Which was the response to the latest registration attacks
=> feat: mainnet compatibility

Cargo.lock, pallets/governance/Cargo.toml, pallets/governance/src/lib.rs, pallets/governance/src/migrations.rs, pallets/governance/src/proposal.rs
This PR:
> Adds a new system that rewards proposal voters every X blocks as described [here](https://coda.io/d/_de30Z7xoDpG/Incentives_sun2g)
Closes #103
=> feat(pallets/governance): add voting rewards

pallets/subnet_emission/src/distribute_emission.rs, pallets/subnet_emission/src/lib.rs, pallets/subspace/src/lib.rs, pallets/subspace/src/subnet_consensus/linear.rs, pallets/subspace/src/subnet_consensus/mod.rs, pallets/subspace/src/subnet_consensus/yuma.rs
=> refac: use yuma as a model on linear

Cargo.lock, pallets/subnet_emission/Cargo.toml, pallets/subnet_emission/src/lib.rs, pallets/subnet_emission/src/subnet_pricing/root.rs, pallets/subspace/src/global.rs, pallets/subspace/src/lib.rs, pallets/subspace/src/math.rs, pallets/subspace/src/migrations.rs, pallets/subspace/src/registration.rs, pallets/subspace/src/set_weights.rs
=> feat: implement rootnet emission

.repos, .vscode/settings.json, Cargo.toml, pallets/faucet/Cargo.toml, pallets/faucet/src/lib.rs, pallets/governance/Cargo.toml, pallets/subnet_emission/src/subnet_consensus/linear.rs, pallets/subnet_emission/src/subnet_consensus/yuma.rs, pallets/subspace/Cargo.toml, pallets/subspace/src/lib.rs, pallets/subspace/src/math.rs, pallets/subspace/src/registration.rs, pallets/subspace/src/set_weights.rs
=> refac(pallets/subpsace): use dispatch results

pallets/subspace/src/registration.rs
=> feat: early return on non registerable subnets

pallets/subspace/src/subnet.rs
=> feat: make some `SubnetChangeset::validate_param` checks exclusive to mineable subnets

Cargo.lock, pallets/subnet_emission/Cargo.toml, pallets/subnet_emission/api/src/lib.rs, pallets/subnet_emission/src/distribute_emission.rs, pallets/subnet_emission/src/lib.rs, pallets/subnet_emission/src/migrations.rs, pallets/subspace/src/migrations.rs, runtime/src/lib.rs, tests/src/mock.rs
=> feat: adding subnet migrations

pallets/subspace/src/lib.rs, pallets/subspace/src/staking.rs, tests/src/mock.rs, tests/src/root.rs, tests/src/subnet_emission.rs, tests/src/subspace/registration.rs, tests/src/subspace/staking.rs, tests/src/subspace/subnet.rs, tests/src/subspace/weights.rs
=> feat(pallets/subspace): minimum allowed stake

CHANGELOG.md, pallets/faucet/src/lib.rs, pallets/governance/src/proposal.rs, pallets/governance/src/voting.rs, pallets/subnet_emission/src/subnet_consensus/linear.rs, pallets/subnet_emission/src/subnet_consensus/yuma.rs, pallets/subnet_emission/src/subnet_pricing/root.rs, pallets/subspace/src/lib.rs, pallets/subspace/src/migrations.rs, pallets/subspace/src/registration.rs, pallets/subspace/src/set_weights.rs, pallets/subspace/src/staking.rs, tests/src/mock.rs, tests/src/subnet_emission.rs, tests/src/subspace/registration.rs, tests/src/subspace/staking.rs
=> feat: remove stake storage value

pallets/subspace/src/subnet.rs, tests/src/subspace/registration.rs
=> test: remove subnet dangling keys

pallets/subnet_emission/src/lib.rs, pallets/subnet_emission/src/migrations.rs, tests/src/subnet_emission.rs
=> feat: automatically raise unit emission

pallets/governance/src/lib.rs, pallets/subnet_emission/src/distribute_emission.rs, pallets/subspace/src/global.rs, pallets/subspace/src/lib.rs, pallets/subspace/src/migrations.rs, pallets/subspace/src/subnet.rs, tests/src/governance.rs, tests/src/subnet_emission.rs, tests/src/subspace/registration.rs, tests/src/subspace/subnet.rs
=> feat: subnet immunity period

pallets/subspace/src/lib.rs, pallets/subspace/src/migrations.rs, runtime/src/lib.rs, tests/src/mock.rs, tests/src/subspace/subnet.rs
=> feat: move storage DefaultMinValidatorStake to pallet Config

pallets/governance/src/benchmarking.rs, pallets/subnet_emission/src/subnet_consensus/yuma.rs, pallets/subspace/src/benchmarking.rs, pallets/subspace/src/lib.rs, pallets/subspace/src/subnet.rs, tests/src/subnet_emission.rs
=> feat: add validator blacklist

CHANGELOG.md, Cargo.lock, pallets/governance/Cargo.toml, pallets/governance/src/voting.rs, runtime/src/lib.rs
=> fix: false `InsufficientStake` error

pallets/offworker/src/lib.rs, pallets/subnet_emission/api/src/lib.rs, pallets/subnet_emission/src/lib.rs, pallets/subnet_emission/src/set_weights.rs, pallets/subnet_emission/src/subnet_consensus/linear.rs, pallets/subnet_emission/src/subnet_consensus/util/consensus.rs, pallets/subnet_emission/src/subnet_consensus/util/params.rs, pallets/subnet_emission/src/subnet_consensus/yuma.rs, pallets/subnet_emission/src/subnet_pricing/root.rs, pallets/subspace/src/lib.rs, pallets/subspace/src/module.rs, pallets/subspace/src/rpc.rs, pallets/subspace/src/subnet.rs, runtime/src/lib.rs, tests/src/mock.rs, tests/src/root.rs, tests/src/subnet_emission.rs, tests/src/subspace/weights.rs
=> refac: move weight pallet

Cargo.lock, Cargo.toml, node/Cargo.toml, pallets/faucet/Cargo.toml, pallets/governance/Cargo.toml, pallets/governance/api/Cargo.toml, pallets/subnet_emission/Cargo.toml, pallets/subnet_emission/api/Cargo.toml, pallets/subspace/Cargo.toml, pallets/subspace/rpc/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs, runtime/src/precompiles.rs
This adds back evm support, it has everything except dynamic fee which i don't consider important
=> feat: adding evm back

node/Cargo.toml, node/src/cli.rs, node/src/command.rs, node/src/main.rs, node/src/rpc/mod.rs, node/src/service.rs, node/src/service/manual_seal.rs, runtime/src/lib.rs
=> flagging eth related functionality
